apiVersion: v1
kind: Secret

metadata:
  name: staynest-secret

type: Opaque

stringData:
  CLOUD_NAME: "your_cloud_name"
  API_KEY: "your_api_key"
  API_SECRET: "your_api_secret"

  MAPBOX_TOKEN: "your_mapbox_token"

  MONGO_URL: "your_mongodb_url"

  SECRET: "your_secret"